enrichment_plugin:
  ZUESTRACKER_DOMAIN_SOURCE: https://zeustracker.abuse.ch/blocklist.php?download=baddomains
  ZUESTRACKER_IP_SOURCE: https://zeustracker.abuse.ch/blocklist.php?download=badips
  ZUESTRACKER_URL_SOURCE: https://zeustracker.abuse.ch/blocklist.php?download=compromised