enrichment_plugin:
  ZEUSTRACKER_DOMAIN_SOURCE: https://zeustracker.abuse.ch/blocklist.php?download=baddomains
  ZEUSTRACKER_IP_SOURCE: https://zeustracker.abuse.ch/blocklist.php?download=badips
  ZEUSTRACKER_URL_SOURCE: https://zeustracker.abuse.ch/blocklist.php?download=compromised
